KDN-2115 and KDN-2030
Klarrio/Cachet pull request #3
Opened 2020-12-08 01:23 UTC by Tejas-Waje

2020-12-08 13:19 UTC, kiefersmith commented on resources/lang/af-ZA/notifications.php
> +                'title'   => 'A new DSH maintenance schedule is announced.',
"is announced" sounds off.

2020-12-08 13:20 UTC, kiefersmith commented on resources/lang/ar-SA/notifications.php
> +                'title'   => 'A new DSH maintenance schedule is announced.',
I would write "has been announced" instead of "is announced".

2020-12-08 13:23 UTC, kiefersmith reviewed
I would change all instances of "is announced" to "has been announced".  Maybe "is announced" makes sense in context, not sure.

2020-12-09 01:51 UTC, Tejas-Waje commented
I agree, but, the change was specifically requested by AJ
https://klarrio.atlassian.net/browse/KDN-2115?focusedCommentId=22528

2020-12-09 08:16 UTC, rpartapsing requested changes
@Tejas-Waje you want to merge into 2.4? Better to create a new version no?
This repo is forked. I think if you push you to 2.4 this is for all cachet users publicly

2020-12-10 22:51 UTC, Tejas-Waje commented
> @Tejas-Waje you want to merge into 2.4? Better to create a new version no?
> This repo is forked. I think if you push you to 2.4 this is for all cachet users publicly

Thanks, @rpartapsing, created a new branch [2.4.6](https://github.com/Klarrio/Cachet/tree/2.4.6) from [2.4.5.2](https://github.com/Klarrio/Cachet/tree/2.4.5.2) and changed the base of this PR to [2.4.6](https://github.com/Klarrio/Cachet/tree/2.4.6).
Also, I plan to create a release from it.

2020-12-10 22:52 UTC, rpartapsing approved these changes

2020-12-21 00:13 UTC, merged